default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: book_collection_development
  host: localhost
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

test:
  <<: *default
  database: book_collection_test
  host: localhost
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # Explicitly remove host, username, password to avoid conflicts
  host: <%= nil %>
  username: <%= nil %>
  password: <%= nil %>